# Generated by Django 3.0.8 on 2022-01-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prijzen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='Heren', max_length=200, unique=True)),
                ('betaalWijze', models.CharField(choices=[('Contant', 'Contant'), ('Pin', 'Pin'), ('Pin of Contant', 'pin of Contant')], default='Contant', max_length=20, unique=True)),
                ('knipPrijs', models.DecimalField(decimal_places=2, default=0, max_digits=6, unique=True)),
                ('contourPrijs', models.DecimalField(decimal_places=2, default=0, max_digits=6, unique=True)),
                ('tondeusePrijs', models.DecimalField(decimal_places=2, default=0, max_digits=6, unique=True)),
                ('baardPrijs', models.DecimalField(decimal_places=2, default=0, max_digits=6, unique=True)),
                ('waxPrijs', models.DecimalField(decimal_places=2, default=0, max_digits=6, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Prijzen',
            },
        ),
    ]
