# Generated by Django 3.0.8 on 2022-01-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prijzen',
            name='knipPrijs',
        ),
        migrations.AddField(
            model_name='prijzen',
            name='nieuweKlantPrijs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='prijzen',
            name='vasteKlantPrijs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prijzen',
            name='baardPrijs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prijzen',
            name='betaalWijze',
            field=models.CharField(choices=[('Contant', 'Contant'), ('Pin', 'Pin'), ('Pin of Contant', 'pin of Contant')], default='Contant', max_length=20),
        ),
        migrations.AlterField(
            model_name='prijzen',
            name='contourPrijs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prijzen',
            name='tondeusePrijs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prijzen',
            name='waxPrijs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
