# Generated by Django 3.0.8 on 2022-01-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_auto_20220114_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(default=' ', max_length=200)),
                ('achternaam', models.CharField(default=' ', max_length=200)),
                ('email', models.EmailField(default=' ', max_length=200)),
                ('bericht', models.TextField(default=' ', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
