# Generated by Django 3.0.8 on 2022-01-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='prijzen',
            name='extra',
            field=models.CharField(choices=[('Tikkie toegestaan', 'Tikkie toegestaan'), ('Geen tikkie', 'Geen tikkie')], default='Geen tikkie', max_length=20),
        ),
    ]
