# Generated by Django 3.0.8 on 2022-01-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_prijzen_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prijzen',
            name='extra',
            field=models.CharField(choices=[('Andere betaal wijze niet toegestaan', 'Andere betaal wijze niet toegestaan'), ('Andere betaal wijze toegestaan', 'Andere betaal wijze toegestaan')], default='Andere betaal wijze niet toegestaan', max_length=255),
        ),
    ]
