# Generated by Django 3.0.8 on 2022-01-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_auto_20220127_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='achternaam',
        ),
    ]
