# Generated by Django 3.0.8 on 2021-12-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('appointment_id', models.CharField(default='', max_length=20, unique=True)),
                ('Naam', models.CharField(default='Anonymous', help_text='Name of the person', max_length=20)),
                ('Achternaam', models.CharField(default='Anonymous Surname', help_text='Surname of the person', max_length=20)),
                ('Nummer', models.CharField(default='+31 6', help_text='Contact phone number', max_length=20, null=True)),
                ('Tijd', models.CharField(choices=[('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00')], default='11:00', max_length=20, unique=True)),
                ('keuze', models.CharField(choices=[('ALLEEN HAAR', 'ALLEEN HAAR'), ('ALLEEN BAARD', 'ALLEEN BAARD'), ('HAAR + BAARD', 'HAAR + BAARD')], default='ALLEEN HAAR', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'appointments',
            },
        ),
    ]
