# Generated by Django 3.0.8 on 2021-12-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveAgenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='anoniem',
            field=models.CharField(choices=[('JA', 'JA'), ('NEE', 'NEE')], default='NEE', max_length=20),
        ),
    ]
